#!/bin/bash
echo "=== GPU MACHINE INFO ==="
echo "Host: $(hostname)"
echo "User: $(whoami)"
echo "OS: $(cat /etc/os-release | grep PRETTY_NAME | cut -d'"' -f2)"
echo "Kernel: $(uname -r)"
echo "CPU: $(lscpu | grep 'Model name' | cut -d':' -f2 | xargs)"
echo "Memory: $(free -h | grep Mem | awk '{print $2}')"
echo "Disk Space: $(df -h / | tail -1 | awk '{print $4 " available of " $2}')"
echo ""
echo "=== GPU INFO ==="
nvidia-smi --query-gpu=index,name,memory.total,memory.used --format=csv,noheader,nounits
echo ""
echo "=== CUDA VERSION ==="
nvcc --version 2>/dev/null || echo "CUDA not found in PATH"