apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api-v1
  labels:
    app: llm-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-api
      version: v1
  template:
    metadata:
      labels:
        app: llm-api
        version: v1
    spec:
      containers:
      - name: llm-server
        image: llm-api:v1
        imagePullPolicy: IfNotPresent 
        env:
        - name: MODEL_NAME
          value: "microsoft/phi-2"
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "4Gi"
            cpu: "2"
          requests:
            nvidia.com/gpu: "1"
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: llm-api-service
spec:
  selector:
    app: llm-api
  ports:
  - port: 80
    targetPort: 8000
  type: NodePort